config/routes.rb
Rails.application.routes.draw do
  root 'vehiculos#index'
  resources :vehiculos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehiculo.rb
class Vehiculo < ApplicationRecord
    validates :titulo, presence: true
    validates :descripcion, presence: true
    has_one_attached :img
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
    def index
        @vehiculos =
        if params[:buscar]
            Vehiculo.where('titulo ILIKE ?', "%#{params[:buscar]}%").order(created_at: :desc).per_page_kaminari(params[:pagina]) ||
            Vehiculo.where('descripcion ILIKE ?', "%#{params[:buscar]}%").order(created_at: :desc).per_page_kaminari(params[:pagina])
        else
            Vehiculo.all.order(created_at: :desc).per_page_kaminari(params[:pagina])
        end
    end
    
      def show
        @vehiculo = Vehiculo.find(params[:id])
      end
    
      def new
        @vehiculo = Vehiculo.new
      end
    
      def create
        @vehiculo = Vehiculo.new(vehiculo_params)
    
        if @vehiculo.save
          redirect_to @vehiculo
        else
          render :new
        end
      end
    
      def edit
        @vehiculo = Vehiculo.find(params[:id])
      end
    
      def update
        @vehiculo = Vehiculo.find(params[:id])
    
        if @vehiculo.update(vehiculo_params)
          redirect_to @vehiculo
        else
          render :edit
        end
      end
    
      def destroy
        @vehiculo = Vehiculo.find(params[:id])
        @vehiculo.destroy
    
        redirect_to root_path
      end
    
      private
        def vehiculo_params
          params.require(:vehiculo).permit(:titulo, :descripcion, :img)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vehiculos - Modulo 8</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="AIEP 0061" />
    <meta name="author" content="Jose Duarte" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
  </head>

  <body>
            <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Gestion Vehiculos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Inicio</a></li>
                        <li class="nav-item"><%= link_to "Nuevo!", new_vehiculo_path, class: "nav-link" %></li>
                        <li class="nav-item"><%= link_to "Github", 'https://github.com/saert3311/vehiculos-m8', class: "nav-link", target: '_blank' %></li>
                    </ul>
                  <%= form_with url: '/vehiculos', class: 'd-flex',method: :get, local: true do |f| %>
                    <%= f.text_field :buscar, class: 'form-control me-2', type: 'search', placeholder: 'Buscar' %>
                    <%= f.submit "Buscar", class: 'btn btn-outline-success', type: 'submit' %>
                  <% end %>
                </div>
            </div>
        </nav>
    <%= yield %>
          <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Vehiculos 2021</p></div>
        </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/vehiculos/_form.html.erb
<%= form_with model: vehiculo do |f| %>
    <div class="mb-3">
        <%= f.label :titulo, 'Titulo:', class: 'form-label' %>
        <%= f.text_field :titulo, class: 'form-control' %>
        <% vehiculo.errors.full_messages_for(:titulo).each do |msj| %>
            <div class="invalid-feedback">
                <%= msj %>
            </div>
        <% end %>
    </div>

    <div class="mb-3">
        <%= f.label :descripcion, 'Descripcion:', class: 'form-label' %>
        <%= f.text_area :descripcion, class: 'form-control' %><br>
        <% vehiculo.errors.full_messages_for(:descripcion).each do |msj| %>
            <div class="invalid-feedback">
                <%= msj %>
            </div>
        <% end %>
    </div>

    <div class="mb-3">
        <%= f.label :img, 'Imagen:', class: 'form-label mb-3'%>
        <%= f.file_field :img, class: 'form-control' %>
        <% vehiculo.errors.full_messages_for(:img).each do |msj| %>
            <div class="invalid-feedback">
                <%= msj %>
            </div>
        <% end %>
    </div>
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>
<% end %>

app/views/vehiculos/edit.html.erb
<div class="container-fluid">
    <div class="row align-items-center justify-content-center min-vh-100">
        <div class="col-sm-4">
            <div class="card">
            <div class="card-header">
                <h5 class="card-title text-center mb-0">Editar Vehiculo</h5>
            </div>
                <div class="card-body mb-3">
                    <%= render "form", vehiculo: @vehiculo %>
                </div>
                <div class="card-footer d-md-flex justify-content-md-end">
                    <%= link_to 'Volver', vehiculo_path(@vehiculo), class: "btn btn-secondary" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/vehiculos/index.html.erb
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Vehiculos</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Los mas nuevos</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <% @vehiculos.each do |v| %>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <%= v.img.attached? ?
                               image_tag(v.img, class: "img-fluid rounded") :
                               image_tag('https://picsum.photos/450/300?random=' + v.id.to_s, class: 'img-fluid rounded') %>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%= v.titulo %></h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="<%= vehiculo_path(v) %>">Ver</a></div>
                            </div>
                        </div>
                    </div>
                <% end %>
                </div>
            </div>
        </section>
        <<%= paginate @vehiculos %>

app/views/vehiculos/new.html.erb
<div class="container-fluid">
    <div class="row align-items-center justify-content-center min-vh-100">
        <div class="col-sm-4">
            <div class="card">
            <div class="card-header">
                <h5 class="card-title text-center mb-0">Nuevo Vehiculo</h5>
            </div>
                <div class="card-body mb-3">
                    <%= render "form", vehiculo: @vehiculo %>
                </div>
                <div class="card-footer d-md-flex justify-content-md-end">
                    <%= link_to 'Volver', root_path, class: "btn btn-secondary" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/vehiculos/show.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
        <div class="mb-3">
            <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1"><%= @vehiculo.titulo %></h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2"><%= @vehiculo.created_at.strftime("%m de %B") %></div>
                                <%= link_to "Editar", edit_vehiculo_path(@vehiculo), class: "btn btn-secondary btn-sm" %>
    <%= link_to "Eliminar", vehiculo_path(@vehiculo), class: "btn btn-danger btn-sm",
        method: :delete,
        data: {confirm: "Estas seguro?"}  %>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4">
                        <%= @vehiculo.img.attached? ? 
                        image_tag(@vehiculo.img, class: "img-fluid rounded", style: "width: 900px; height: 400px; object-fit: cover;") : 
                        image_tag('https://picsum.photos/900/400?random=' + @vehiculo.id.to_s, class: 'img-fluid rounded') %></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4"><%= @vehiculo.descripcion %></p>
                        </section>
                    </article>
</div>
</div>